language: php

php:
   - 5.6

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

brnaches:
  only:
    - master
before_script:
    - mysql -e 'create database test;'
    - cp app/config/testing/database.ci.php  app/config/testing/database.php  #copy over CI environment configuration | database conv
    - travis_retry composer self-update
    - travis_retry composer install --prefer-source --no-interaction --dev
    - chmod -R 777 app/storage/
    - yes | php artisan migrate
    - yes | php artisan db:seed
    - php -S localhost:8000 -t public &
    - sleep 5 # give artisan serve some time to start
    - vendor/bin/codecept build
    - cp tests/acceptance.suite.yml.ci tests/acceptance.suite.yml #copy over CI acceptance test configuration
    # should I do this to all other suites ?

script:
  - php vendor/bin/codecept run --report --coverage-xml


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload  --format=php-clover tests/_output/coverage.xml
after_failure:
  - cat app/storage/logs/laravel.log
  - cat tests/_output/*