language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm


matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

brnaches:
  only:
    - master
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  -php vendor/bin/codecept-run --report --coverage-xml


after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token=<<access token>> --format=php-clover tests/_output/coverage.xml
after_failure:
  - cat app/storage/logs/laravel.log
  - cat tests/_output/*